Wizard logic
jelena-petkovic-ey/MissionToMars pull request #4
Opened 2021-07-16 07:16 UTC by jelena-petkovic-ey

2021-07-16 11:45 UTC, MilanovicM requested changes
### Jelena, great job! 
#### Your application looks awesome!

These are some things that could be improved:
- Address line 2 shouldn't be labeled as a mandatory field;
- City field could be input, similar as state input. The cities dropdown is rendered above the section with possibly long list of entries. This UX practice could be improved.
- Postal code field is behaving in an odd way - we can enter unlimited number on digits, although there are values in the dropdown. Some kind of validation would be useful here.
- There is typo in the "Terms and Conditions" link label (in the Footer).

- Kudos for very good UI/UX, for including progress bar, back button functionality. Overall, everything looks really good.
- Also, please look into the failing request (for saving an applicant) -  I wasn't able to save an applicant because of error 400: 
![image](https://user-images.githubusercontent.com/46046446/125942275-a218383b-8f50-4bdc-adea-c98de99a3e13.png)

2021-07-16 11:45 UTC, MilanovicM commented on src/components/step3/Step3.js
> +import axios from "axios";
It's not good practice to import axios directly inside the component. This should be abstracted to separate http service. For example, if we decide to ditch axios and use fetch or any other library, in that case, we would need to go into each component where axios is imported and change code.

2021-07-16 11:45 UTC, MilanovicM commented on src/components/step3/Step3.js
> +    doesHaveAgricultureSkills: values.doesHaveAgricultureSkills,
Good place for useReducer hook.

2021-07-16 11:45 UTC, MilanovicM commented on src/components/step3/Step3.js
> +  let numOfInputs = [];
Good place to move code to a function.

2021-07-16 11:45 UTC, MilanovicM commented on src/components/step3/Step3.js
> +                  handleCheck={(e) => handleCheck(e)}
We don't need to use anon function to pass event here.

2021-07-16 11:45 UTC, MilanovicM commented on src/components/step3/Step3.js
> +          <label>
This piece of code could be easily extracted into separate component - since it's being reused in multiple places: 
![image](https://user-images.githubusercontent.com/46046446/125939554-38e5bb0b-d7ad-4874-a65c-56854ffb7897.png)
Just an idea :)

2021-07-16 11:45 UTC, MilanovicM commented on src/components/validateForm/ValidateFormStep1.js
> +const ValidateFormStep1 = ({ firstName, lastName }) => {
This is more of a helper (utils) function, and not React component. Should be moved to separate folder, outside of components.

2021-07-16 11:45 UTC, MilanovicM commented on src/constans/initialState.js
> +export const initialState = {
Good job on keeping this as a constant.

2021-07-16 11:45 UTC, MilanovicM commented on src/contexts/FormContext.js
> +    axios
All logic for making API calls should be abstracted. Please see comment above (axios mentioned). 
[Useful article](https://netbasal.com/the-importance-of-abstraction-in-js-ea27e07e996) (see under Example Two - HTTP)

2021-07-16 11:45 UTC, MilanovicM commented on src/contexts/FormContext.js
> +        setPostalCodes(res.data);
This could be shortened to .then( ( { data } ) => setPostalCodes( data ) );

2021-07-16 11:45 UTC, MilanovicM commented on src/contexts/FormContext.js
> +        console.log(e.message);
Please remove console logs. Maybe we can show an error (custom) message on the page, if API returns error response.

2021-07-16 11:45 UTC, MilanovicM commented on src/pages/wizard/Wizard.js
>      switch (currentStep) {
Maybe instead of using switch, we could've used object  literal here?  Please see [this article](https://ultimatecourses.com/blog/deprecating-the-switch-statement-for-object-literals).

2021-07-19 10:02 UTC, jelena-petkovic-ey commented on src/components/inputReason/InputReason.js
> +      if (newState > 5) {
because user is able to add max 5 fields... but I will pass this value as a prop

2021-07-21 20:53 UTC, MilanovicM commented
Jelena, code-wise, everything looks good - great job on refactoring the code ;) I was able to create applicants, yay!

However, there is an issue with requests for fetching states and cities. The API calls are made on each input change - which triggers multiple requests simultaneously. This blocks the UI. It's good practice to add debounce, to prevent this behavior. 

![image](https://user-images.githubusercontent.com/46046446/126557126-215311b5-2c95-4f6b-ac99-62becdd4eaef.png)

Maybe this [article](https://ankit-saxena2605.medium.com/implementing-debouncing-in-react-f3316ef344f5) can be a good starting point for the solution :) 

Also, addressService could be maybe renamed to HttpService, or something similar to indicate that it's going to be used for API calls. It could have e.g. methods for get, post, put , etc. This way we could reuse them in multiple places. 

Example:
![image](https://user-images.githubusercontent.com/46046446/126558614-37bc2a16-f371-4cfd-936b-a28e82148ce8.png)


Method for getAddressData returns a promise after calling axios.get - it doesn't work only for addresses. I like the idea though :) 🎉 
Keep up the awesome work!

2021-07-22 12:01 UTC, MilanovicM approved these changes
Jelena, awesome job on adding tests! 
Please see my other comments :) 
In general, there are still a few improvements to add. 
Also, maybe we can keep data for the carousel in the context, so we don't need to call NASA API each time we go to home page :)
Overall, application works as expected, and has really beautiful UI  :)

## 🥇  Congratulations!!!!

2021-07-22 12:18 UTC, merged